title: 'Product Category'
sections:
  main:
    display: Main
    fields:
      -
        handle: category_description
        field:
          type: textarea
          display: 'Category Description'
      -
        handle: category_hero_image
        field:
          type: assets
          container: main
          restrict: false
          max_files: 1
          display: 'Category hero image'
      -
        handle: system_category
        field:
          type: terms
          max_items: 1
          mode: tags
          display: 'System Category'
          taxonomies:
            - system_category
taxonomies: true
