category_description: '[need category description about storing your records properly etc.]'
category_hero_image: record-storage.jpg
title: Cabinets
system_category: setting
blueprint: product_category
