category_description: 'The Swiss Army knives of audio. Moon, Unico, McIntosh, and others.'
category_hero_image: cddue_1.jpg
title: Multi-function
system_category: multi-function
blueprint: product_category
