category_description: 'Picture a water pipe, where you want maximum flow and low resistance. After market power cables have the ability to bring out the best in your components, especially amplifiers and pre-amps.'
category_hero_image: shunyata-venom-power.jpg
title: 'Power Cables'
system_category: cables
blueprint: product_category
