category_description: 'Think of the preamp as the heart of any system - all sources feed through the preamp, which provides switching between them as well as gain control (volume) and various other signal processing. Many preamps offer options for digital signal processing (DAC) or phono processing (MM/MC) as well.'
category_hero_image: c8-angle.jpg
title: 'Pre Amps'
system_category: amplification
blueprint: product_category
