taxonomies:
  product-categories: products/{slug}

collections:
  products: products/{product-categories}/{slug}
  manufacturers: manufacturers/{slug}
  pre-owned: pre-owned/{slug}

routes:
  /feed.json: FeedController@json